# Generated by Django 2.0.6 on 2018-06-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('descricao', models.CharField(blank=True, default=None, max_length=500)),
                ('created', models.DateField(blank=True, default=None)),
                ('edited', models.DateField(blank=True, default=None)),
                ('removed', models.DateField(blank=True, default=None)),
                ('concluded', models.DateField(blank=True, default=None)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
