# Generated by Django 2.0.6 on 2018-06-14 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20180614_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='task',
            name='concluded',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created',
        ),
        migrations.RemoveField(
            model_name='task',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='task',
            name='removed',
        ),
    ]
